### ISSUE TITLE
Support generate reference documentation for ORAS CLI from the source code

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-www#59]
ORAS CLI has a detailed help doc with examples in source code, I believe it is also a good reference for new users to learn or query on the website. We would like to generate the help doc for ORAS CLI from the source code and display it on the ORAS website.

[kubectl reference documentation](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands) is a good example. The K8s community explained the process of generating the reference documentation in this [guide](https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/). 

Updates:
It sounds not easy to re-use the kubectl reference doc framework. Now we are using Cobra to [generate the markdown files](https://umarcor.github.io/cobra/#documentation-generation) and then add them to the website manually.

**Need help**: we are also looking to build an automation tool to help maintain this process by a bot 🤖

**Comment by FeynmanZhou** [comment]
Hi @qweeah , could you pls help to investigate if this can be provided on the ORAS website?

**Comment by qweeah** [comment]
Sure, will start to investigate how much effort to auto-generate the web reference page.

**Comment by qweeah** [comment]
@FeynmanZhou I have investigated how the command reference doc is generated. The conclusion is that this tool cannot be directly reused in oras CLI since it's **deeply coupled with kubectl code**. I didn't dig deep but it seems we can cut its dependency from [kubectl](https://pkg.go.dev/k8s.io/kubectl/pkg/cmd) to [cobra command](https://pkg.go.dev/github.com/spf13/cobra#Command) but that requires extra coding effort.

Basically the [doc page](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands) can be generate via [gen-kubectldocs](https://pkg.go.dev/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs) module and then hosted with a nodejs container. To generate a reference page, there are two inputs:
1) a spec: kubectl root command object used to generate markdown docs via [cobra markdown doc generation](https://pkg.go.dev/github.com/spf13/cobra@v1.6.1/doc#GenManTree)
2) a template: yaml file that divide commands into different groups for viewing

The output includes
  - a html index page generated based on markdown
  -  js event files for scrolling, navigating and etc
  - css files for formatting

The generation process is done via golang code which **deeply coupled with kubectl implementation (input 1)**

To generate oras cli reference doc page based on [gen-kubectldocs](https://pkg.go.dev/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs), we need to do below tasks
1) Refactor oras CLI implementation so the root cmd object is accessible via external modules
2) Improve [gen-kubectl](https://pkg.go.dev/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs): change its dependency from [kubectl](https://pkg.go.dev/k8s.io/kubectl/pkg/cmd) to [cobra command](https://pkg.go.dev/github.com/spf13/cobra#Command)
3) Write our own templates (per LTS version)

**Comment by qweeah** [comment]
For task 2, since [gen-kubectldocs](https://pkg.go.dev/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs) is designed for kubectl I can foresee the pushback from k8s community. Another option is we fork the module and do what ever we want in our fork. But we need to make extra effort to cherry-pick whatever is merged in upstream.

**Comment by FeynmanZhou** [comment]
It sounds not easy to re-use the kubectl reference doc framework. We can still use Cobra to [generate the markdown files](https://umarcor.github.io/cobra/#documentation-generation) and then add them to the website.

**Comment by FeynmanZhou** [comment]
@qweeah I generated the CLI reference docs using Cobra for all commands. So I adjust the content and layout and then create a new chapter in the ORAS documentation.

**Comment by qweeah** [comment]
Besides generating web content directly, do we need to provide any utility to generate the command markdown docs?
